---
- name: Install i3
  pacman: name=i3-wm

- name: Install acpilight (xbacklight replacement)
  aur: name=acpilight skip_installed=yes
  become: yes
  become_user: aurbuild

- name: Create group video
  group: name=video state=present

- name: Add local users to the video group
  user: name={{ item }} groups=video append=yes
  with_items: '{{ users }}'

- name: Copy udev settings for acpilight
  copy: src=files/etc/udev/90-backlight.rules dest=/etc/udev/rules.d/90-backlight.rules mode=644

- name: Install redshift
  aur: name=redshift-minimal skip_installed=yes
  become_user: aurbuild

- name: Copy redshift service definition
  copy: src=files/lib/systemd/redshift.service dest=/usr/lib/systemd/user/redshift.service mode=644
  register: redshift

  # FIXME: This does not seem to work properly. The service is started without error but there is no red tint.
- name: Enable redshift service
  command: systemctl --user --global enable redshift.service
  when: redshift.changed
  # systemd: name=redshift.service enabled=yes scope=global

- name: Install dmenu
  pacman: name=dmenu

- name: Install document utilities (AUR)
  aur: name=zotero
  become: yes
  become_user: aurbuild

- name: Install terminal emulator
  pacman: name=alacritty

- name: Install document viewer
  pacman: name=mupdf

- name: Install image viewer
  pacman: name=gpicview-gtk3

- name: Install archiver
  pacman: name=xarchiver

- name: Install browser
  pacman:
    name:
    - chromium
    - firefox
    - firefox-i18n-de
    - firefox-i18n-en-gb
    - firefox-i18n-en-us
    - libu2f-host
    # Add-ons are synchronised via the Firefox Account
    #- firefox-decentraleyes
    #- firefox-extension-https-everywhere
    #- firefox-extension-privacybadger
    #- firefox-referer-control
    #- firefox-ublock-origin

- name: Install file manager
  pacman:
    name:
    - gvfs
    - pcmanfm-gtk3

- name: Install sound utilities
  pacman:
    name:
    - pulseaudio
    - playerctl
    - alsa-utils

- name: Create /etc/environment.d/
  file: path=/etc/environment.d state=directory mode=0755

- name: HiDPI configuration
  when: hidpi
  copy: src=files/etc/environment.d/90-hidpi.conf dest=/etc/environment.d/90-hidpi.conf mode=644
