---
- name: Write locale.conf
  copy: src=files/etc/locale.conf dest=/etc/locale.conf
  register: locale_config

- name: Write locale.gen
  copy: src=files/etc/locale.gen dest=/etc/locale.gen
  register: locale_gen

- name: Update locales
  command: locale-gen
  when: locale_config.changed or locale_gen.changed
