---
- name: Install reflector
  pacman: name=reflector

- name: Set up reflector.service
  copy: src=files/lib/systemd/reflector.service dest=/etc/systemd/system/reflector.service
  register: service

- name: Set up reflector.timer
  copy: src=files/lib/systemd/reflector.timer dest=/etc/systemd/system/reflector.timer
  register: timer

- name: Reload daemon
  when: service.changed or timer.changed
  systemd: daemon_reload=yes

- name: Start and enable reflector timer
  systemd: name=reflector.timer state=started enabled=yes
