---
- name: Install command line utilities
  pacman:
    name:
    - acpi
    - agda
    - aria2
    - bash-completion
    - dstat
    - fd
    - fzf
    - dos2unix
    - htop
    - python-virtualenv
    - ripgrep
    - tmux
    - unzip
    - tree
    - vim

- name: Install command line utilities (AUR)
  aur:
    name:
    - direnv
  become_user: aurbuild

- name: Install Terminus tty font
  pacman: name=terminus-font

- name: Set up tty font and keymap
  copy: src=files/etc/vconsole.conf dest=/etc/vconsole.conf mode=644

- name: Install mono (requirement for vim-youcompleteme-git)
  pacman: name=mono

- name: Install YouCompleteMe
  aur: name=vim-youcompleteme-git skip_installed=yes
  become_user: aurbuild
